version: '3.9'  # Use the appropriate version of Docker Compose

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"  # Map port 8000 on the host to port 80 in the container
    volumes:
      - wordpress_data:/var/www/html  # Persist WordPress data across containers
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data across containers
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass

volumes:
  wordpress_data:
  db_data:
